  - type: software
    date-released: 2023-07-05
    version: 4.3.11
    abstract: A full featured, fast Command Line Argument Parser for Rust
    authors:
      - alias: kbknapp
        family-names: Knapp
        given-names: Kevin B.
      - name: The Clap Community
    license:
      - Apache-2.0
      - MIT
    repository-artifact: https://crates.io/crates/clap
    repository-code: https://github.com/clap-rs/clap
    title: clap
    url: https://docs.rs/clap
