  - type: software
    date-released: 2023-08-01
    version: 0.6.2
    abstract: The system exit codes as defined by <sysexits.h> for Rust
    authors:
      - alias: sorairolake
        family-names: Sakai
        given-names: Shun
      - alias: kevinmatthes
        family-names: Matthes
        given-names: Kevin
    license:
      - Apache-2.0
      - MIT
    repository-artifact: https://crates.io/crates/sysexits
    repository-code: https://github.com/sorairolake/sysexits-rs
    title: sysexits-rs
    url: https://docs.rs/sysexits
