######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Run `cargo update` and create a PR for the changes.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        cargo-update.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: cargo-update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - run: rustup update

      - uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - uses: fregante/setup-git-user@v2.0.1

      - run: |
          cargo update
          git add .
          git commit --allow-empty -m 'Changed ::= ``cargo update``'

      - uses: peter-evans/create-pull-request@v5.0.1
        with:
          assignees: |
            kevinmatthes
          branch: feature/cargo-update
          branch-suffix: timestamp
          labels: |
            enhancement
          milestone: 5
          title: '[GitHub Actions] cargo update'

################################################################################
