######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Assemble the main CITATION.cff from its updated fragments.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        cff.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: cff

on:
  push:
    branches:
      - main
    paths:
      - .github/CFF/*.cff
      - .github/CFF/*.yml
      - Cargo.toml
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    if: github.repository == 'kevinmatthes/aeruginous-rs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: fregante/setup-git-user@v2.0.1
      - run: rustup update

      - run: |
          curl \
            https://raw.githubusercontent.com/chronotope/chrono/main/CITATION.cff \
            | cargo r -- cffreference > .github/CFF/chrono.yml
          git add .github/CFF/chrono.yml
          git commit --allow-empty -m \
            '[GitHub Actions] Update CFF Entry for chrono'

      - run: |
          curl \
            https://raw.githubusercontent.com/clap-rs/clap/master/CITATION.cff \
            | cargo r -- cffreference > .github/CFF/clap.yml
          git add .github/CFF/clap.yml
          git commit --allow-empty -m \
            '[GitHub Actions] Update CFF Entry for Clap'

      - run: |
          curl \
            https://raw.githubusercontent.com/sorairolake/sysexits-rs/develop/CITATION.cff \
            | cargo r -- cffreference > .github/CFF/sysexits.yml
          git add .github/CFF/sysexits.yml
          git commit --allow-empty -m \
            '[GitHub Actions] Update CFF Entry for sysexits-rs'

      - run: |
          cat .github/CFF/aeruginous.cff > CITATION.cff
          {
            echo references: ;
            cat .github/CFF/chrono.yml \
                .github/CFF/citation-file-format.yml \
                .github/CFF/clap.yml \
                .github/CFF/sysexits.yml ;
          } >> CITATION.cff
          git add .
          git commit --allow-empty -m '[GitHub Actions] Assemble CITATION.cff'

      - uses: peter-evans/create-pull-request@v5.0.2
        with:
          assignees: |
            kevinmatthes
          branch: documentation/cff-update
          branch-suffix: timestamp
          labels: documentation
          milestone: 6
          title: '[GitHub Actions] Update CITATION.cff'

################################################################################
