######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Assemble this project's CITATION.cff.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        cff.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: cff

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/CFF/*.cff
      - .github/CFF/*.yml

permissions:
  contents: write

jobs:
  assembly:
    if: github.repository == 'kevinmatthes/aeruginous-rs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: fregante/setup-git-user@v2.0.1

      - run: |
          cat .github/CFF/aeruginous.cff           >  CITATION.cff
          echo references:                         >> CITATION.cff
          cat .github/CFF/chrono.yml               >> CITATION.cff
          cat .github/CFF/citation-file-format.yml >> CITATION.cff
          cat .github/CFF/clap.yml                 >> CITATION.cff
          cat .github/CFF/sysexits.yml             >> CITATION.cff
          git add .
          git commit --allow-empty -m '[GitHub Actions] Assemble CITATION.cff'
          git push

################################################################################
