######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Update the README when changing `src/lib.rs`.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        mirror.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: mirror

on:
  push:
    branches:
      - main
    paths:
      - src/lib.rs
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  readme:
    if: github.repository == 'kevinmatthes/aeruginous-rs'
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2.21.15
        with:
          tool: cargo-llvm-cov

      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11

      - run: rustup update

      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: echo pycobertura >> requirements.txt
      - uses: fregante/setup-git-user@v2.0.1
      - uses: py-actions/py-dependency-install@v4.1.0

      - run: |
          cargo llvm-cov --cobertura --output-path cobertura.xml
          sed "s/<!-- cov -->.*<!-- cov -->/<!-- cov -->$( \
            pycobertura show -f csv --delimiter , cobertura.xml | \
            grep TOTAL | \
            cut -d, -f4)<!-- cov -->/g" src/lib.rs >> lib.rs
          mv lib.rs src/
          git add src/lib.rs
          git commit --allow-empty -m \
            "[GitHub Actions] Update Coverage in src/lib.rs"

      - run: |
          cargo r -- rs2md -i src/lib.rs --outer -o README.md
          git add README.md
          git commit --allow-empty -m \
            "[GitHub Actions] Mirror README.md from src/lib.rs"

      - uses: peter-evans/create-pull-request@v5.0.2
        with:
          assignees: |
            kevinmatthes
          branch: documentation/mirror
          branch-suffix: timestamp
          labels: |
            documentation
          milestone: 6
          title: '[GitHub Actions] Mirror README.md from src/lib.rs'

################################################################################
