######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Update the README when changing `src/lib.rs`.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        mirror.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: mirror

on:
  push:
    branches:
      - main
    paths:
      - src/lib.rs

permissions:
  contents: write

jobs:
  readme:
    name: readme
    runs-on: ubuntu-latest
    steps:
      - name: rustup
        run: rustup update

      - name: checkout
        uses: actions/checkout@v3.5.1

      - name: user
        uses: fregante/setup-git-user@v2.0.1

      - name: update
        run: |
          cargo r -- rs2md -i src/lib.rs --outer -o README.md \
          && git add README.md \
          && git commit --allow-empty -m \
                 "`git config --list \
                 | grep user\.name \
                 | cut -d= -f2`:  Mirror README.md from src/lib.rs" \
          && git push

################################################################################
