######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Upgrade the minimal supported Rust version automatically.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        msrv.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: msrv

on:
  schedule:
    - cron: '0 0 * * TUE'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    name: upgrade
    runs-on: ubuntu-latest
    steps:
      - run: rustup update

      - uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - uses: fregante/setup-git-user@v2.0.1

      - run: |
          MSRV=$(rustc --version | cut d\  -f2)
          sed s/^msrv\ =\ \".*\"/msrv\ =\ \"$(MSRV)"/g \
              .clippy.toml >> .clippy.toml.tmp
          mv .clippy.toml.tmp .clippy.toml
          sed s/^rust-version\ =\ \".*\"/rust-version\ =\ \"$(MSRV)\"/g \
              Cargo.toml >> Cargo.toml.tmp
          mv Cargo.toml.tmp Cargo.toml
          git add .clippy.toml Cargo.toml
          git commit --allow-empty -m "Changed ::= MSRV:  $(MSRV)"

      - uses: peter-evans/create-pull-request@v5.0.1
        with:
          assignees: |
            kevinmatthes
          branch: documentation/msrv
          branch-suffix: timestamp
          labels: |
            enhancement
          milestone: 4
          title: '[GitHub Actions] Upgrade MSRV'

################################################################################
